config/routes.rb
Doctify::Application.routes.draw do
  get "home/index"

  resources :docs do
       get 'search', :on => :collection 
  end

  root :to => "home#index"

end

app/models/doc.rb
class Doc < ActiveRecord::Base
    def self.search(search)
        search_condition = "%" + search + "%"
        find(:all, :conditions => [ 'name LIKE ? OR brief LIKE ? or fulldocument LIKE ?', search_condition, search_condition, search_condition])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  # GET /docs
  # GET /docs.xml
  def index
    @docs = Doc.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @docs }
    end
  end

  # GET /docs/1
  # GET /docs/1.xml
  def show
    @doc = Doc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @doc }
    end
  end

  # GET /docs/new
  # GET /docs/new.xml
  def new
    @doc = Doc.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @doc }
    end
  end

  # GET /docs/1/edit
  def edit
    @doc = Doc.find(params[:id])
  end

  # POST /docs
  # POST /docs.xml
  def create
    @doc = Doc.new(params[:doc])

    respond_to do |format|
      if @doc.save
        format.html { redirect_to(@doc, :notice => 'Doc was successfully created.') }
        format.xml  { render :xml => @doc, :status => :created, :location => @doc }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @doc.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /docs/1
  # PUT /docs/1.xml
  def update
    @doc = Doc.find(params[:id])

    respond_to do |format|
      if @doc.update_attributes(params[:doc])
        format.html { redirect_to(@doc, :notice => 'Doc was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @doc.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.xml
  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy

    respond_to do |format|
      format.html { redirect_to(docs_url) }
      format.xml  { head :ok }
    end
  end
  def search
    @docs = Doc.search params[:search]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/docs/_form.html.erb
<%= form_for(@doc) do |f| %>
  <% if @doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% @doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :shortdesc %><br />
    <%= f.text_field :shortdesc %>
</div>

  <div class="field">
    <%= f.label :brief %><br />
    <%= f.text_field :brief %>
  </div>
  <div class="field">
    <%= f.label :fulldocument %><br />
    <%= f.text_area :fulldocument %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Editing doc</h1>

<%= render 'form' %>

<%= link_to 'Show', @doc %> |
<%= link_to 'Back', docs_path %>

app/views/docs/index.html.erb
<h1>Listing docs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Short Description</th>
    <th>Brief</th>
    <th>Full Document</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @docs.each do |doc| %>
  <tr>
    <td><%= doc.name %></td>
    <td><%= doc.shortdesc %></td>
    <td><%= doc.brief %></td>
    <td><%= doc.fulldocument %></td>
    <td><%= link_to 'Show', doc %></td>
    <td><%= link_to 'Edit', edit_doc_path(doc) %></td>
    <td><%= link_to 'Destroy', doc, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Doc', new_doc_path %>

app/views/docs/new.html.erb
<h1>New doc</h1>

<%= render 'form' %>

<%= link_to 'Back', docs_path %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="section-header">
      <span class="section-title">Name</span>
</div>
<div class="section-content">
      <%= @doc.name %>
</div>
<div class="section-header">
    <span class="section-title">Short description</span>
 </div>
<div class="section-content">
       <%= @doc.shortdesc %>
</div>
<div class="section-header">
  <span class="section-title">Brief:</span>
 </div>
<div class="section-content">
 <%= @doc.brief %>
</div>
<div class="section-header">
    <span class="section-title">Full:</span>
  </div>
<div class="section-content">
  <%= @doc.fulldocument.html_safe %>
</div>

<%= link_to 'Edit', edit_doc_path(@doc) %> |
<%= link_to 'Back', docs_path %>

app/views/home/index.html.erb
A short example for today:

git

Brief:
git-core
git-show
git-commit
git-log

Full:

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doctify.com | search geek stuff in style</title>
  <link rel="canonical" href="http://doctify.com/" />
  <link  href="http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:200,300,400,700" rel="stylesheet" type="text/css" >
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'screen', :media => 'screen' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="container">
    <div id="header" class="clearfix">
        <div id="strip" class="clearfix">
            <div id="st" class="clearfix">
                <h1>
                    <a href="http://doctify.com">Doctify.</a>
                </h1>
                <div id="search">
                <%= render :partial => 'docs/search' %>
                </div>
            </div>
            <div id="dr">
                <p>
                    Search for manuals and docs in style.
                </p>
                <p>
                    All your information that you are looking for is here is a smart format.
                </p>
                <p>
                    Go ahead, try it.
                </p>
        </div>
    </div>
   </div>
    <div id="content">
        <div id="content-strip">
        <%= yield %>
        </div>
    </div>
    <div id="footer">
        <div id="footer-box">
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/">Contact</a></li>
                <li><a href="/">FAQ</a></li>
            </ul>
        </div>
    </div>
<div>
</body>
</html>